name: 'Install Dependencies'
description: 'Installs wheel and third-party dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Setup python by installing wheel
      run: pip install wheel==0.35.0
      shell: bash
    - name: Install python 2 for GAE
      run: |
        sudo apt update
        sudo apt install python2 -y
      shell: bash
    - uses: ./.github/actions/install-third-party-libraries
