name: Todo Check

on:
  issues:
    types: [closed, reopened]
  pull_request:
    types: [opened]
    branches:
      - develop
  merge_group:
    types: [checks_requested]
    branches:
      - develop

permissions:
  issues: write
  pull-requests: write

jobs:
  issue_check:
    if: github.event_name == 'issues'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: ./.github/actions/merge
    
      - name: Check for unresolved todos
        id: check_for_unresolved_todos
        run: |
          python -m scripts.check_for_unresolved_todos --repository_path=$(pwd) --issue=${{ github.event.issue.number }} --commit_sha=${{ github.sha }}

      - name: Reopen issue
        if: failure() && steps.check_for_unresolved_todos.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue reopen ${{ github.event.issue.number }}
    
      - name: Check for duplicate todo comment
        id: check_for_duplicate_todo_comment
        if: failure() && steps.check_for_unresolved_todos.outcome == 'failure'
        run: |
          python -m scripts.check_for_duplicate_todo_comment --repository_path=$(pwd) --issue=${{ github.event.issue.number }} --new_comment_file=unresolved_todo_list.txt

      - name: Add Comment
        if: failure() && steps.check_for_duplicate_todo_comment.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} -F $(pwd)/unresolved_todo_list.txt
  pull_request_check:
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - uses: ./.github/actions/merge
        
      - name: Check for unresolved todos
        id: check_for_unresolved_todos
        run: |
          python -m scripts.check_for_unresolved_todos --repository_path=$(pwd) --pull_request=${{ github.event.pull_request.number }} --commit_sha=${{ github.sha }}

      - name: Check for duplicate todo comment
        id: check_for_duplicate_todo_comment
        if: failure() && steps.check_for_unresolved_todos.outcome == 'failure'
        run: |
          python -m scripts.check_for_duplicate_todo_comment --repository_path=$(pwd) --pull_request=${{ github.event.pull_request.number }} --new_comment_file=unresolved_todo_list.txt

      - name: Add Comment
        if: failure() && steps.check_for_duplicate_todo_comment.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F $(pwd)/unresolved_todo_list.txt
